version: '3.8'

services:
  voice-assistant:
    build: .
    container_name: verbi-voice-assistant
    volumes:
      # Mount models directory for persistence
      - ./piper_models:/app/piper_models
      # Mount for audio files
      - ./audio_files:/app/audio_files
      # Mount config if needed
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      # For Windows audio support
      - PULSE_SERVER=host.docker.internal:4713
    network_mode: bridge
    ports:
      - "8000:8000"
      - "5150:5150"
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - ollama
    
  # Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped

volumes:
  ollama_data:
